### ISSUE TITLE
 SCRIPT ERROR  handler (@mi-hauler/server/main.lua:48)

### ISSUE THREAD

**Issue by balcer64** [irsyadf27/mi-hauler#2]
![screenshot25](https://user-images.githubusercontent.com/22128071/142915735-4679a889-ec4b-4e89-b2f7-994f3c5d2709.png)
I press the "E" button, an error in the logs, but otherwise everything works, what is it and how to fix it, can you tell me?

script:qb-core] SCRIPT ERROR: @qb-core/server/player.lua:243: attempt to perform arithmetic on a nil value (field '?')
 script:qb-core] > ref (@qb-core/server/player.lua:243)
 handler (@mi-hauler/server/main.lua:48)

**Comment by irsyadf27** [comment]
> ![screenshot25](https://user-images.githubusercontent.com/22128071/142915735-4679a889-ec4b-4e89-b2f7-994f3c5d2709.png) I press the "E" button, an error in the logs, but otherwise everything works, what is it and how to fix it, can you tell me?
> 
> script:qb-core] SCRIPT ERROR: @qb-core/server/player.lua:243: attempt to perform arithmetic on a nil value (field '?') script:qb-core] > ref (@qb-core/server/player.lua:243) handler (@mi-hauler/server/main.lua:48)

just comment code at line 48
`Player.Functions.AddJobReputation(1)`

it just script to add player job reputation

**Comment by balcer64** [comment]
thanks
